namespace ServicoF1.Models.F1.CRMExterno
{
    public class CrmExterno
    {
        public int id { get; set; }
        public int f1_id { get; set; }
        public string code { get; set; }
        public object segment_id { get; set; }
        public string person_type { get; set; }
        public string cgc { get; set; }
        public string name_fancy { get; set; }
        public string name_corporate { get; set; }
        public string registration_state { get; set; }
        public string registration_municipal { get; set; }
        public string phone_number { get; set; }
        public string cell_phone_number { get; set; }
        public object date_of_birth { get; set; }
        public string email { get; set; }
        public string email_invoice { get; set; }
        public string email_orders { get; set; }
        public object external_segment_code { get; set; }
        public object price_list { get; set; }
        public string credit { get; set; }
        public object allow_post_payment { get; set; }
        public object average_payment_period { get; set; }
        public string tax_regime { get; set; }
        public object minimum_order_value { get; set; }
        public object maximum_order_value { get; set; }
        public string suframa_code { get; set; }
        public object suframa_expiration_date { get; set; }
        public object created { get; set; }
        public string default_operation_type { get; set; }
        public string address_street { get; set; }
        public string address_number { get; set; }
        public string address_complement { get; set; }
        public string address_state { get; set; }
        public string address_city { get; set; }
        public string address_neighborhood { get; set; }
        public string address_country { get; set; }
        public object address_reference { get; set; }
        public string address_zipcode { get; set; }
        public string address_ibge_code { get; set; }
        public string delivery_address_street { get; set; }
        public string delivery_address_number { get; set; }
        public string delivery_address_complement { get; set; }
        public string delivery_address_state { get; set; }
        public string delivery_address_city { get; set; }
        public string delivery_address_neighborhood { get; set; }
        public string delivery_address_country { get; set; }
        public object delivery_address_reference { get; set; }
        public string delivery_address_zipcode { get; set; }
        public string delivery_address_ibge_code { get; set; }
        public string charge_address_street { get; set; }
        public string charge_address_number { get; set; }
        public string charge_address_complement { get; set; }
        public string charge_address_state { get; set; }
        public string charge_address_city { get; set; }
        public string charge_address_neighborhood { get; set; }
        public string charge_address_country { get; set; }
        public object charge_address_reference { get; set; }
        public string charge_address_zipcode { get; set; }
        public string charge_address_ibge_code { get; set; }
        public int integrated { get; set; }
        public object integrated_message { get; set; }
        public int active { get; set; }
        public object export_date { get; set; }
        public int modified { get; set; }
        public string created_at { get; set; }
        public string updated_at { get; set; }
        public object deleted_at { get; set; }
        public string updated_for { get; set; }
        public int moderated { get; set; }
        public object billing_distribution_center { get; set; }
        public object default_order_type { get; set; }
        public object exclusive_payment_method_condition_installment { get; set; }
        public int responsible_crm_user_id { get; set; }
        public string responsible_crm_user_type { get; set; }
        public string responsible_crm_user_name { get; set; }
        public string responsible_crm_user_mail { get; set; }
        public string responsible_crm_user_external_code { get; set; }
        public string responsible_crm_client_external_code { get; set; }
        public string simples_code { get; set; }
    }
}