//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoF1.Uteis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServicoF1.Uteis.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select
        ///            ISNULL(T0.Active, &apos;&apos;) AS &apos;Contato Ativo&apos;, --0
        ///            ISNULL(T0.Position, &apos;Geral&apos;) AS &apos;Contato posicao&apos;, --1
        ///            ISNULL(T0.Name, &apos;&apos;) AS &apos;Contato Nome&apos;, --2
        ///            ISNULL(T0.E_MailL, &apos;&apos;) AS &apos;Contato E-mail&apos;, --3
        ///            0 AS &apos;is_telesales&apos;, --4
        ///            0 AS &apos;purchasing_limit&apos;, --5
        ///            1 AS &apos;visualize_only_owned_orders&apos;, --6
        ///            0 AS &apos;permission_place_orders&apos;, --7
        ///            0 AS &apos;permission_open_rma&apos;, --8
        ///            0 AS &apos;permission_get_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Busca_Contatos {
            get {
                return ResourceManager.GetString("Busca_Contatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///            CASE
        ///            WHEN LEN(T2.TaxId0) &gt; 0 THEN TaxId0  
        ///            WHEN LEN(T2.TaxId4) &gt; 0 THEN TaxId4
        ///            END AS &apos;cgc&apos;, -- 1
        ///            ISNULL(T0.CardCode, &apos;&apos;) AS &apos;CardCode&apos;,--2
        ///            CASE
        ///            WHEN LEN(T2.TaxId0) &gt; 0 THEN &apos;J&apos;
        ///            WHEN LEN(T2.TaxId4) &gt; 0 THEN &apos;F&apos;
        ///            END AS &apos;Tipo Pessoa&apos;,--3
        ///            T4.TributType AS &apos;tax_regime&apos;, --4
        ///            ISNULL(T0.AliasName, &apos;&apos;) AS &apos;Nome Estrângeiro&apos;, --5
        ///            ISNULL(T0.CardName, &apos;&apos;) &apos;C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Busca_Parceiro {
            get {
                return ResourceManager.GetString("Busca_Parceiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///distinct
        ///&apos;*&apos; as ItemCode, a.NcmCode as Ncm, &apos;*&apos; as &apos;client_cnpj&apos;, &apos;*&apos; as &apos;city_destination&apos;, &apos;*&apos; as &apos;home_state&apos;, &apos;*&apos; as &apos;destination_state&apos;, 
        ///&apos;*&apos; as &apos;production_origin&apos;, &apos;*&apos; as &apos;tax_regime&apos;, &apos;*&apos; as &apos;sell_type&apos;, &apos;*&apos; as &apos;nature_operation&apos;, b.u_Aliquota as &apos;ipi&apos; 
        ///from 
        ///oncm a 
        ///inner join oncg b on a.&quot;Group&quot;=b.&quot;GroupCode&quot; 
        ///inner join oitm c on c.NCMCode=a.AbsEntry
        ///where a.&quot;Group&quot; is not null AND U_CadastrarF1 = &apos;Y&apos;.
        /// </summary>
        internal static string Busca_Tributos_IPI {
            get {
                return ResourceManager.GetString("Busca_Tributos_IPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @tiposChave table 
        ///(id int,
        /// descr char(30))
        ///insert into @tiposChave (id, descr) values (1,&apos;PN&apos;)
        ///insert into @tiposChave (id, descr) values (2,&apos;ITEM&apos;)
        ///insert into @tiposChave (id, descr) values (3,&apos;GRUPO_DE_MATERIAIS&apos;)
        ///insert into @tiposChave (id, descr) values (5,&apos;NCM&apos;)
        ///insert into @tiposChave (id, descr) values (6,&apos;UF&apos;)
        ///insert into @tiposChave (id, descr) values (9,&apos;GRUPO_DE_ITEM&apos;)
        ///insert into @tiposChave (id, descr) values (11,&apos;GRUPO_DE_CLIENTES&apos;)
        ///insert into @tiposChave (id, descr) val [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Busca_tributos_por_uso {
            get {
                return ResourceManager.GetString("Busca_tributos_por_uso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///T0.CardCode,
        ///ISNULL(sum(CASE when datediff(d,duedate, GETDATE())&gt;0 then 1 else 0 end), 0) as Quantidade
        ///
        /// 
        ///
        ///FROM  
        ///[dbo].[OINV] T0  
        ///INNER  JOIN [dbo].[INV6] T1  ON  T1.DocEntry = T0.DocEntry  
        ///LEFT OUTER JOIN  (
        ///SELECT T1.InstId,T0.CardCode,T1.DocEntry Nro_pagamento,max(T0.DocDate) Data_Pagamento
        ///FROM  [dbo].[ORCT] T0  INNER  JOIN [dbo].[RCT2] T1  ON  T1.DocNum = T0.DocEntry   
        ///WHERE  T0.Canceled = &apos;N&apos;  AND  T1.InvType = &apos;13&apos;
        ///GROUP BY T1.InstId,T0.CardCode,T1.DocEntry) PAG 
        ///ON PAG.CardCode=T0.CardC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContasEmAtraso {
            get {
                return ResourceManager.GetString("ContasEmAtraso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT AbsId, KeyFld_1, KeyFld_2, KeyFld_3, KeyFld_4, KeyFld_5 FROM TCD1 WHERE AbsId in (SELECT Code FROM &quot;@F1_IPI_PARAMS&quot;) order by Priority ASC.
        /// </summary>
        internal static string Determinacoes_IPI {
            get {
                return ResourceManager.GetString("Determinacoes_IPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &quot;Docentry&quot;, &quot;BaseEntry&quot; from DPI1 where BaseEntry = (Select top 1 DocEntry FROM ORDR WHERE NumAtCard = &apos;{card}&apos; AND CANCELED = &apos;N&apos; ORDER BY DocEntry desc).
        /// </summary>
        internal static string Find_Adiantamento {
            get {
                return ResourceManager.GetString("Find_Adiantamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &quot;Docentry&quot; FROM ORDR WHERE NumAtCard = &apos;{card}&apos; AND CANCELED = &apos;N&apos;.
        /// </summary>
        internal static string Find_Order {
            get {
                return ResourceManager.GetString("Find_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T2.DocEntry  FROM RCT2  T0 INNER JOIN ORCT  T1 ON T0.&quot;DocNum&quot; = T1.&quot;DocEntry&quot; 
        ///INNER JOIN ODPI T2 ON T0.&quot;DocEntry&quot; = T2.&quot;DocEntry&quot;
        ///Where T0.InvType = 203 and T2.DocEntry = (Select TOP 1 &quot;Docentry&quot; from DPI1 where BaseEntry = (Select top 1 DocEntry FROM ORDR WHERE NumAtCard = &apos;{card}&apos; AND CANCELED = &apos;N&apos; ORDER BY DocEntry desc)).
        /// </summary>
        internal static string Find_Pagamento {
            get {
                return ResourceManager.GetString("Find_Pagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @tiposChave table
        ///(id int,
        ///descr char(30))
        ///insert into @tiposChave (id, descr) values (1,&apos;PN&apos;) -- OCRD
        ///insert into @tiposChave (id, descr) values (2,&apos;ITEM&apos;) --OITM
        ///insert into @tiposChave (id, descr) values (3,&apos;GRUPO_DE_MATERIAIS&apos;) --OMGP
        ///insert into @tiposChave (id, descr) values (5,&apos;NCM&apos;) --ONCM
        ///insert into @tiposChave (id, descr) values (6,&apos;UF&apos;) --
        ///insert into @tiposChave (id, descr) values (9,&apos;GRUPO_DE_ITEM&apos;) --OUGP
        ///insert into @tiposChave (id, descr) values (11,&apos;GRUPO_DE_CLIENTES&apos;) --OCRG 
        ///inse [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Impostos_IPI {
            get {
                return ResourceManager.GetString("Impostos_IPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T1.FldValue, T1.Descr FROM CUFD T0 LEFT JOIN UFD1 T1 ON T0.FieldID = T1.FieldID AND T0.TableID = T1.TableID
        ///WHERE T0.TableID = &apos;OCRD&apos; AND T0.AliasID = &apos;area_negocio&apos; AND T1.FldValue is not null.
        /// </summary>
        internal static string Segmentos {
            get {
                return ResourceManager.GetString("Segmentos", resourceCulture);
            }
        }
    }
}
